Creating test database for alias 'default'...
......E
======================================================================
ERROR: test_retrieve_todo (todoapi.tests.TodoTests)
Ensure that we can retrieve todos
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rootdev/py/dj_rest/todo/todoapi/tests.py", line 160, in test_retrieve_todo
    self.assertEqual(response.data.results, serializer.data)
AttributeError: 'collections.OrderedDict' object has no attribute 'results'

----------------------------------------------------------------------
Ran 7 tests in 1.662s

FAILED (errors=1)
Destroying test database for alias 'default'...
